import type { Product, Order, OrderStatusColorMap, ProductStatusColorMap } from "./types/ProductTypes";

export const products: Product[] = [
  { id: 1, productName: "Wireless Over-Ear Headphones", category: "Electronics", price: 199.99, stock: 45, status: "in stock" },
  { id: 2, productName: "Heavyweight Graphic Hoodie", category: "Streetwear", price: 85.00, stock: 120, status: "in stock" },
  { id: 3, productName: "Mechanical Gaming Keyboard", category: "Electronics", price: 150.00, stock: 0, status: "out of stock" },
  { id: 4, productName: "Slim-Fit Chino Pants", category: "Menswear", price: 65.00, stock: 85, status: "in stock" },
  { id: 5, productName: "Noise Cancelling Earbuds", category: "Electronics", price: 129.50, stock: 30, status: "in stock" },
  { id: 6, productName: "Seamless Yoga Leggings", category: "Activewear", price: 55.00, stock: 200, status: "in stock" },
  { id: 7, productName: "Oversized Denim Jacket", category: "Outerwear", price: 110.00, stock: 12, status: "low stock" },
  { id: 8, productName: "4K Curved Monitor", category: "Electronics", price: 450.00, stock: 5, status: "low stock" },
  { id: 9, productName: "Leather Crossbody Bag", category: "Accessories", price: 120.00, stock: 40, status: "in stock" },
  { id: 10, productName: "Performance Running Shoes", category: "Footwear", price: 145.00, stock: 60, status: "in stock" },
  { id: 11, productName: "Minimalist Quartz Watch", category: "Accessories", price: 195.00, stock: 15, status: "low stock" },
  { id: 12, productName: "Merino Wool Sweater", category: "Menswear", price: 95.00, stock: 25, status: "in stock" },
  { id: 13, productName: "USB-C Fast Charger", category: "Electronics", price: 25.00, stock: 500, status: "in stock" },
  { id: 14, productName: "Windbreaker Rain Coat", category: "Outerwear", price: 75.00, stock: 33, status: "in stock" },
  { id: 15, productName: "Retro Canvas Sneakers", category: "Footwear", price: 60.00, stock: 110, status: "in stock" },
  { id: 16, productName: "Vintage Wash Denim Jeans", category: "Menswear", price: 89.00, stock: 55, status: "in stock" },
  { id: 17, productName: "Silk Evening Gown", category: "Womenswear", price: 299.00, stock: 10, status: "low stock" },
  { id: 18, productName: "Water-Resistant Windbreaker", category: "Outerwear", price: 120.00, stock: 42, status: "in stock" },
  { id: 19, productName: "Cotton Crewneck Tee (3-Pack)", category: "Essentials", price: 45.00, stock: 150, status: "in stock" },
  { id: 20, productName: "Cashmere Turtleneck", category: "Womenswear", price: 180.00, stock: 15, status: "low stock" },
  { id: 21, productName: "Leather Biker Jacket", category: "Outerwear", price: 350.00, stock: 8, status: "low stock" },
  { id: 22, productName: "Compression Workout Shorts", category: "Activewear", price: 40.00, stock: 90, status: "in stock" },
  { id: 23, productName: "Wool Blend Peacoat", category: "Outerwear", price: 220.00, stock: 20, status: "in stock" },
  { id: 24, productName: "High-Top Canvas Sneakers", category: "Footwear", price: 75.00, stock: 65, status: "in stock" },
  { id: 25, productName: "Polarized Retro Sunglasses", category: "Accessories", price: 110.00, stock: 30, status: "in stock" },
  { id: 26, productName: "Linen Button-Down Shirt", category: "Menswear", price: 70.00, stock: 48, status: "in stock" },
  { id: 27, productName: "Suede Chelsea Boots", category: "Footwear", price: 160.00, stock: 22, status: "in stock" },
  { id: 28, productName: "Graphic Streetwear Hoodie", category: "Streetwear", price: 95.00, stock: 110, status: "in stock" },
  { id: 29, productName: "Velvet Slip Dress", category: "Womenswear", price: 130.00, stock: 14, status: "low stock" },
  { id: 30, productName: "Knitted Beanie Cap", category: "Accessories", price: 25.00, stock: 300, status: "in stock" },
  { id: 31, productName: "Yoga Mat Carrier Bag", category: "Activewear", price: 35.00, stock: 50, status: "in stock" },
  { id: 32, productName: "Formal Oxford Shoes", category: "Footwear", price: 140.00, stock: 18, status: "low stock" },
  { id: 33, productName: "Puffer Down Vest", category: "Outerwear", price: 115.00, stock: 25, status: "in stock" },
  { id: 34, productName: "Smart Home Security Camera", category: "Electronics", price: 89.99, stock: 60, status: "in stock" },
  { id: 35, productName: "Ergonomic Office Chair", category: "Electronics", price: 299.00, stock: 15, status: "low stock" },
  { id: 36, productName: "Dual-Band Wi-Fi 6 Router", category: "Electronics", price: 149.00, stock: 35, status: "in stock" },
  { id: 37, productName: "Portable Bluetooth Speaker", category: "Electronics", price: 59.50, stock: 80, status: "in stock" },
  { id: 38, productName: "Ultra-Wide Gaming Monitor", category: "Electronics", price: 550.00, stock: 0, status: "out of stock" },
  { id: 39, productName: "Wireless Charging Pad", category: "Electronics", price: 29.99, stock: 250, status: "in stock" },
  { id: 40, productName: "Smart Fitness Watch", category: "Electronics", price: 199.00, stock: 45, status: "in stock" },
  { id: 41, productName: "USB-C Mechanical Keyboard", category: "Electronics", price: 110.00, stock: 28, status: "in stock" },
  { id: 42, productName: "4K Action Camera", category: "Electronics", price: 249.00, stock: 20, status: "in stock" },
  { id: 43, productName: "Tablet Stylus Pen", category: "Electronics", price: 79.00, stock: 100, status: "in stock" },
  { id: 44, productName: "External 2TB SSD", category: "Electronics", price: 160.00, stock: 55, status: "in stock" },
  { id: 45, productName: "Noise-Cancelling Mic", category: "Electronics", price: 135.00, stock: 40, status: "in stock" },
  { id: 46, productName: "Laptop Cooling Pad", category: "Electronics", price: 35.00, stock: 75, status: "in stock" },
  { id: 47, productName: "Smart LED Light Strip", category: "Electronics", price: 45.00, stock: 180, status: "in stock" },
  { id: 48, productName: "Professional DSLR Camera", category: "Electronics", price: 1200.00, stock: 3, status: "low stock" },
  { id: 49, productName: "Wireless Trackball Mouse", category: "Electronics", price: 65.00, stock: 90, status: "in stock" },
  { id: 50, productName: "E-Reader Paper Tablet", category: "Electronics", price: 189.00, stock: 32, status: "in stock" },
  { id: 51, productName: "Mini Drone with 1080p", category: "Electronics", price: 299.00, stock: 14, status: "low stock" },
];

export const recentOrders: Order[] = [
	{
		orderId: 1,
		customer: "Marcus Aurelius",
		address: "123 Rome Ave, Italy",
		status: "delivered",
		orderDate: "2026-02-01",
		total: 245.5,
	},
	{
		orderId: 2,
		customer: "Serena Williams",
		address: "456 Court St, Florida, USA",
		status: "shipped",
		orderDate: "2026-02-03",
		total: 89.99,
	},
	{
		orderId: 3,
		customer: "David Gandy",
		address: "10 Savile Row, London, UK",
		status: "pending",
		orderDate: "2026-02-05",
		total: 1200.0,
	},
	{
		orderId: 4,
		customer: "Emma Watson",
		address: "22 Oxford St, London, UK",
		status: "processing",
		orderDate: "2026-02-07",
		total: 350.25,
	},
	{
		orderId: 5,
		customer: "Hideo Kojima",
		address: "7-1 Ginza, Tokyo, Japan",
		status: "delivered",
		orderDate: "2026-02-08",
		total: 512.0,
	},
	{
		orderId: 6,
		customer: "Anya Taylor-Joy",
		address: "99 Hollywood Blvd, CA, USA",
		status: "pending",
		orderDate: "2026-02-09",
		total: 125.0,
	},
	{
		orderId: 7,
		customer: "Virgil Abloh",
		address: "50 Off-White Way, Paris, FR",
		status: "cancelled",
		orderDate: "2026-02-09",
		total: 2100.0,
	},
	{
		orderId: 8,
		customer: "Lewis Hamilton",
		address: "44 Speed Lane, Monaco",
		status: "processing",
		orderDate: "2026-02-10",
		total: 450.0,
	},
	{
		orderId: 9,
		customer: "Zendaya Coleman",
		address: "14 Euphoria Dr, CA, USA",
		status: "delivered",
		orderDate: "2026-02-10",
		total: 890.75,
	},
	{
		orderId: 10,
		customer: "Timothée Chalamet",
		address: "88 Dune Rd, NY, USA",
		status: "pending",
		orderDate: "2026-02-10",
		total: 120.4,
	},
];

export const allOrders: Order[] = [
	{
		orderId: 1,
		customer: "Marcus Aurelius",
		address: "123 Rome Ave, Italy",
		status: "delivered",
		orderDate: "2026-02-01",
		total: 245.5,
	},
	{
		orderId: 2,
		customer: "Serena Williams",
		address: "456 Court St, Florida, USA",
		status: "shipped",
		orderDate: "2026-02-03",
		total: 89.99,
	},
	{
		orderId: 3,
		customer: "David Gandy",
		address: "10 Savile Row, London, UK",
		status: "pending",
		orderDate: "2026-02-05",
		total: 1200.0,
	},
	{
		orderId: 4,
		customer: "Emma Watson",
		address: "22 Oxford St, London, UK",
		status: "processing",
		orderDate: "2026-02-07",
		total: 350.25,
	},
	{
		orderId: 5,
		customer: "Hideo Kojima",
		address: "7-1 Ginza, Tokyo, Japan",
		status: "delivered",
		orderDate: "2026-02-08",
		total: 512.0,
	},
	{
		orderId: 6,
		customer: "Anya Taylor-Joy",
		address: "99 Hollywood Blvd, CA, USA",
		status: "pending",
		orderDate: "2026-02-09",
		total: 125.0,
	},
	{
		orderId: 7,
		customer: "Virgil Abloh",
		address: "50 Off-White Way, Paris, FR",
		status: "cancelled",
		orderDate: "2026-02-09",
		total: 2100.0,
	},
	{
		orderId: 8,
		customer: "Lewis Hamilton",
		address: "44 Speed Lane, Monaco",
		status: "processing",
		orderDate: "2026-02-10",
		total: 450.0,
	},
	{
		orderId: 9,
		customer: "Zendaya Coleman",
		address: "14 Euphoria Dr, CA, USA",
		status: "delivered",
		orderDate: "2026-02-10",
		total: 890.75,
	},
	{
		orderId: 10,
		customer: "Timothée Chalamet",
		address: "88 Dune Rd, NY, USA",
		status: "pending",
		orderDate: "2026-02-10",
		total: 120.4,
	},
	{
		orderId: 11,
		customer: "Timothée Chalamet1",
		address: "88 Dune Rd, NY, USA",
		status: "pending",
		orderDate: "2026-02-10",
		total: 120.4,
	},
];

export const orderStatusColors: OrderStatusColorMap = {
	pending:
		"bg-yellow-100 text-yellow-700 dark:bg-yellow-950/70 dark:text-yellow-300",
	processing:
		"bg-blue-100 text-blue-700 dark:bg-blue-950/70 dark:text-blue-300",
	shipped:
		"bg-purple-100 text-purple-700 dark:bg-purple-950/70 dark:text-purple-300",
	delivered:
		"bg-green-100 text-green-700 dark:bg-green-950/70 dark:text-green-300",
	cancelled: "bg-red-100 text-red-700 dark:bg-red-950/70 dark:text-red-300",
};

export const productStatusColors: ProductStatusColorMap = {
    "in stock": "bg-green-100 text-green-700 dark:bg-green-950/70 dark:text-green-300",
    "out of stock": "bg-red-100 text-red-700 dark:bg-red-950/70 dark:text-red-300",
    "low stock": "bg-yellow-100 text-yellow-700 dark:bg-yellow-950/70 dark:text-yellow-300",
}